apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/your-username/argocd-repo.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: dev

